# Site settings
title: Daniela & Enrique
description: Freelance IT and Content Service
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Daniela & Enrique
user_description: "We're a Freelancer couple working as a Team since 2010."
user_description2: "We're in Argentina (most of the time) working for small and medium size clients around the world, providing infrastructure and content creation services for companies and individuals that require to build their presence online."
user_title: IT and Content Services
email_da: qmax.mail@gmail.com
email_q: da.carrara@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-slate